import { Card, CardContent } from "@/components/ui/card";
import { Sparkles, Download, Zap, Shield, Palette, FileText } from "lucide-react";

const features = [
  {
    icon: Sparkles,
    title: "AI-Powered Technology",
    description: "Our AI signature generator uses advanced machine learning to create unique, professional signatures instantly."
  },
  {
    icon: Download,
    title: "Multiple Formats",
    description: "Download your AI-generated signature in PNG or SVG format for maximum compatibility across all platforms."
  },
  {
    icon: Zap,
    title: "Lightning Fast",
    description: "Generate 10 professional signatures in seconds with our AI signature maker - no waiting required."
  },
  {
    icon: Shield,
    title: "100% Free Forever",
    description: "Our AI signature creator is completely free with no hidden fees, watermarks, or signup requirements."
  },
  {
    icon: Palette,
    title: "Customizable Styles",
    description: "Choose from multiple signature styles inspired by famous personalities or create your own unique style."
  },
  {
    icon: FileText,
    title: "Professional Quality",
    description: "All signatures generated by our AI free signature generator are suitable for legal documents and business use."
  }
];

export const SEOContent = () => {
  return (
    <section className="py-24 bg-gradient-to-b from-background via-secondary/5 to-background">
      <div className="container mx-auto px-4 max-w-6xl">
        <article className="space-y-16">
          {/* Main Intro */}
          <div className="space-y-6 animate-slide-up text-center max-w-4xl mx-auto">
            <h2 className="text-4xl md:text-5xl font-extrabold text-foreground leading-tight">
              The Ultimate <span className="bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent">AI Signature Generator</span> Guide
            </h2>
            <p className="text-lg md:text-xl text-muted-foreground leading-relaxed">
              Discover how our <strong>AI signature generator</strong> uses cutting-edge artificial intelligence to create 
              professional, unique signatures in seconds. Our <strong>AI signature maker</strong> leverages advanced machine 
              learning algorithms to generate authentic-looking signatures that perfectly match your personality and professional needs.
            </p>
          </div>

          {/* Features Grid */}
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <Card key={index} className="border-2 border-border/50 hover:border-primary/50 shadow-[var(--shadow-card)] hover:shadow-[var(--shadow-hover)] transition-all duration-500 group">
                <CardContent className="p-6 space-y-4">
                  <div className="w-14 h-14 bg-gradient-to-br from-primary to-accent rounded-2xl flex items-center justify-center group-hover:scale-110 transition-transform duration-300">
                    <feature.icon className="w-7 h-7 text-white" />
                  </div>
                  <h3 className="text-xl font-bold text-foreground">{feature.title}</h3>
                  <p className="text-muted-foreground leading-relaxed">{feature.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>

          {/* What is AI Signature Generator */}
          <Card className="border-2 border-border/50 shadow-[var(--shadow-card)] bg-gradient-to-br from-card to-secondary/5">
            <CardContent className="p-10 space-y-6">
              <h2 className="text-3xl md:text-4xl font-bold text-foreground">
                What is an <span className="text-primary">AI Signature Generator</span>?
              </h2>
              <p className="text-lg text-muted-foreground leading-relaxed">
                An <strong>AI signature generator</strong> is an innovative online tool powered by artificial intelligence that creates 
                personalized, professional signatures based on your name input. Our <strong>AI signature maker</strong> analyzes millions 
                of signature patterns to generate unique, authentic-looking signatures that reflect your personality and professional 
                identity. Unlike basic signature tools, our <strong>AI signature creator</strong> understands the nuances of handwriting 
                styles, ensuring each generated signature looks naturally written.
              </p>
            </CardContent>
          </Card>

          {/* How It Works */}
          <div className="space-y-8">
            <div className="text-center">
              <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">
                How to Use Our <span className="text-primary">AI Free Signature Generator</span>
              </h2>
              <p className="text-lg text-muted-foreground max-w-3xl mx-auto">
                Creating your perfect signature with our AI signature generator free tool is simple and fast
              </p>
            </div>
            
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
              {[
                {
                  step: "01",
                  title: "Enter Your Name",
                  description: "Type your full name or preferred signature text in the input field. Our AI signature maker will analyze it."
                },
                {
                  step: "02",
                  title: "Choose Options",
                  description: "Select signature length (full or short) and style preferences in the advanced options menu."
                },
                {
                  step: "03",
                  title: "Generate Instantly",
                  description: "Click the generate button and watch as our AI signature creator produces 10 unique signature designs."
                },
                {
                  step: "04",
                  title: "Preview & Select",
                  description: "Review all generated signatures and choose your favorite from the collection of AI-generated options."
                },
                {
                  step: "05",
                  title: "Customize Colors",
                  description: "Pick your preferred signature color to match your brand or personal preference perfectly."
                },
                {
                  step: "06",
                  title: "Download & Use",
                  description: "Download your signature in PNG or SVG format and start using it immediately on documents and emails."
                }
              ].map((item, index) => (
                <Card key={index} className="border-2 border-border/50 hover:border-primary/50 transition-all duration-300 group">
                  <CardContent className="p-6 space-y-4">
                    <div className="text-5xl font-bold text-primary/20 group-hover:text-primary/30 transition-colors">
                      {item.step}
                    </div>
                    <h3 className="text-xl font-bold text-foreground">{item.title}</h3>
                    <p className="text-muted-foreground leading-relaxed">{item.description}</p>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>

          {/* Benefits Section */}
          <Card className="border-2 border-primary/20 shadow-[var(--shadow-hover)] bg-gradient-to-br from-primary/5 to-accent/5">
            <CardContent className="p-10 space-y-8">
              <div className="text-center">
                <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">
                  Why Choose Our <span className="text-primary">AI Signature Generator Free</span> Tool?
                </h2>
                <p className="text-lg text-muted-foreground max-w-3xl mx-auto">
                  Experience the most advanced AI signature maker with unmatched features and quality
                </p>
              </div>
              
              <div className="grid md:grid-cols-2 gap-6">
                {[
                  {
                    title: "Completely Free Forever",
                    description: "Our AI free signature generator never charges fees, requires subscriptions, or adds watermarks to your signatures."
                  },
                  {
                    title: "Professional Quality Output",
                    description: "Generate signatures suitable for legal documents, contracts, business correspondence, and official use with our AI signature creator."
                  },
                  {
                    title: "Multiple Design Styles",
                    description: "Choose from elegant, modern, bold, minimal, and celebrity-inspired signature styles with our AI signature maker."
                  },
                  {
                    title: "Instant Generation",
                    description: "Create 10 unique professional signatures in seconds - no waiting, no complex setup required with our AI signature generator."
                  },
                  {
                    title: "Flexible Export Options",
                    description: "Download signatures in PNG or SVG format for perfect compatibility with all document types and platforms."
                  },
                  {
                    title: "No Account Required",
                    description: "Start creating signatures immediately without signup, registration, or providing personal information."
                  },
                  {
                    title: "Unlimited Generations",
                    description: "Generate as many signature variations as you need until you find the perfect one for your needs."
                  },
                  {
                    title: "Mobile & Desktop Friendly",
                    description: "Use our AI signature generator free tool on any device - phone, tablet, or computer with full functionality."
                  }
                ].map((benefit, index) => (
                  <div key={index} className="flex gap-4 p-6 bg-background/50 rounded-xl border border-border/50">
                    <div className="flex-shrink-0">
                      <div className="w-2 h-2 rounded-full bg-primary mt-2"></div>
                    </div>
                    <div className="space-y-2">
                      <h3 className="text-lg font-bold text-foreground">{benefit.title}</h3>
                      <p className="text-muted-foreground leading-relaxed">{benefit.description}</p>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* Use Cases */}
          <div className="space-y-8">
            <div className="text-center">
              <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">
                Perfect Uses for Your <span className="text-primary">AI-Generated Signature</span>
              </h2>
              <p className="text-lg text-muted-foreground max-w-3xl mx-auto">
                From business documents to personal correspondence, our AI signature creator serves all your needs
              </p>
            </div>
            
            <div className="grid md:grid-cols-3 gap-6">
              {[
                { title: "Legal Documents", items: ["Contracts", "Agreements", "Affidavits", "Wills"] },
                { title: "Business Use", items: ["Email Signatures", "Letters", "Proposals", "Invoices"] },
                { title: "Personal Use", items: ["Letters", "Cards", "Art", "Social Media"] }
              ].map((category, index) => (
                <Card key={index} className="border-2 border-border/50">
                  <CardContent className="p-6 space-y-4">
                    <h3 className="text-xl font-bold text-foreground">{category.title}</h3>
                    <ul className="space-y-2">
                      {category.items.map((item, i) => (
                        <li key={i} className="flex items-center gap-2 text-muted-foreground">
                          <span className="text-accent">✓</span>
                          {item}
                        </li>
                      ))}
                    </ul>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>

          {/* Final CTA */}
          <Card className="border-0 shadow-[var(--shadow-hover)] bg-gradient-hero">
            <CardContent className="p-12 text-center space-y-6">
              <h2 className="text-3xl md:text-4xl font-bold text-white">
                Ready to Create Your Perfect Signature?
              </h2>
              <p className="text-xl text-white/90 max-w-2xl mx-auto leading-relaxed">
                Join thousands of professionals using our <strong>AI signature generator free</strong> tool to create 
                stunning, professional signatures in seconds. No signup required, completely free forever!
              </p>
            </CardContent>
          </Card>
        </article>
      </div>
    </section>
  );
};
